[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "C Maven"
description = "Everything I know about the C programming language that you might also want to know."


# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/c.code-maven.com"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/szabgab/c.code-maven.com/edit/main/{path}"

# Remove the printer icon from the menu
[output.html.print]
enable = false

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"

[preprocessor.alerts]



# This requires the print.html file which will not be created as we set the output.html.print to false.
# [output.pdf]
